### ISSUE TITLE
when I try to go to settings, it just crashes.

### ISSUE THREAD

**Issue by MASTERdjango** [sunilpaulmathew/sNotz#15]
the problem happens if you try with yourphone language in Spanish, but if you set to English it works.
i am a noob, jet.
but I do non know  why and what more info can i give.

**Comment by el-leo-pardo** [comment]
Hello.
Due to I reported the same error and then I saw that it was a translation problem, I finished the translation into Spanish (I have doubts in some cases, due to the use of certain verb modes, above all). However, I don't know how the changes can be applied to the application. I guess it depends on an update of the program.
Regards.

**Comment by sunilpaulmathew** [comment]
> 
> 
> Hello. Due to I reported the same error and then I saw that it was a translation problem, I finished the translation into Spanish (I have doubts in some cases, due to the use of certain verb modes, above all). However, I don't know how the changes can be applied to the application. I guess it depends on an update of the program. Regards.

Thanks a lot. I prepared a test build for you ([attached here](https://www.dropbox.com/s/uzbj39b6hbdtj5p/com.sunilpaulmathew.snotz.apk?dl=0)). The crashes should be fixed. But, can you please test it and tell me if everything okay?
Also, if you're previous installation is from Google Play or F-Droid, you'll need to uninstall the previous one due to the APK signature difference.

**Comment by el-leo-pardo** [comment]
Many thanks to you for this great application and for your caring about the users.
I have already checked the app and it works fine! In addition, I made some additional corrections to the typing and to the context of use. Therefore, please consider the latest version of the translation before publishing the update.
In the future, if I find any other mistake un the translation or if you introduce new features and need translation into Spanish, let me know and I'll take care of it.
Best regards.

**Comment by sunilpaulmathew** [comment]
@el-leo-pardo 
Thanks a lot
