### ISSUE TITLE
[SUGGESTION] Some minor suggestions

### ISSUE THREAD

**Issue by MasterixCZ** [sunilpaulmathew/sNotz#39]
I could think of a few changes that I think would make sNotz better.
1. Changing the settings icon to fit more closely with the other icons. Example:
![Bez názvu](https://user-images.githubusercontent.com/84620639/220403399-56e997b9-c25c-40e3-b081-f22e612e993a.png)

2. This is more of a personal opinion, but I think it would be better for most people to change the default color of the notes to make it look like a real notebook. (maybe even the overall UI and make it fit together). Because the current colors look unprofessional and sometimes ugly in my opinion. Example:
![Bezasd názvu](https://user-images.githubusercontent.com/84620639/220405384-404de31c-b894-4f0d-a272-0aa94e538bbe.png)

3. Is there any way to remove the frames around the colors? This way they look like embedded images. Example:
![PNG](https://user-images.githubusercontent.com/84620639/220406676-4c182c51-91cb-40fc-906e-43e7b6c99c0e.png)

4. And last one, change the icon for adding notes to something more intuitive and clear. Example (rough sketch):
![asd](https://user-images.githubusercontent.com/84620639/220409577-97e22474-03ef-41aa-82eb-affc4ecd2a05.png)

These changes could improve the impression of sNotz.

**Comment by sunilpaulmathew** [comment]
@MasterixCZ 
I hope half of your suggestions are addressed. App now offers changing the accent color (new option in settings menu + show an option to choose colours for newly installed users on first app launch) too so that users might set their favourite colour combination.

Regarding your 3rd suggestion; I'm actually planning to hide that screen by default as it is talking a significant amount of screen space.

![Screenshot_20230225-232126](https://user-images.githubusercontent.com/15515387/221382285-2adc3ca3-5112-4af6-acba-4268f107e911.jpg)
![Screenshot_20230225-232039](https://user-images.githubusercontent.com/15515387/221382290-68e85e5c-7801-4e64-b6b1-abaadb21ee02.jpg)

**Comment by MasterixCZ** [comment]
Great! :)
